### ISSUE TITLE
 TypeError: Cannot read property 'nodeName' of null

### ISSUE THREAD

**Issue by videni** [react-component/form#172]
call stack
```
at getScrollableContainer (node_modules/rc-form/lib/createDOMForm.js:67:27)
      at newCb (node_modules/rc-form/lib/createDOMForm.js:133:40)
      at node_modules/rc-form/lib/createBaseForm.js:452:13
      at complete (node_modules/async-validator/lib/index.js:107:7)
      at node_modules/async-validator/lib/index.js:243:7
      at next (node_modules/async-validator/lib/util.js:170:7)
      at count (node_modules/async-validator/lib/util.js:115:7)
      at cb (node_modules/async-validator/lib/index.js:191:11)
      at Object.string [as validator] (node_modules/async-validator/lib/validator/string.js:42:3)
      at node_modules/async-validator/lib/index.js:234:22
      at node_modules/async-validator/lib/util.js:120:5
          at Array.forEach (<anonymous>)
      at asyncParallelArray (node_modules/async-validator/lib/util.js:119:7)
      at node_modules/async-validator/lib/util.js:178:7
          at Array.forEach (<anonymous>)
      at asyncMap (node_modules/async-validator/lib/util.js:173:14)
      at Schema.validate (node_modules/async-validator/lib/index.js:159:24)
      at Object.validateFieldsInternal (node_modules/rc-form/lib/createBaseForm.js:404:19)
      at Object.validateFields (node_modules/rc-form/lib/createBaseForm.js:485:14)
      at Object.validateFieldsAndScroll (node_modules/rc-form/lib/createDOMForm.js:145:17)
      at OrgForm.handleSubmit.e (src/components/Organization/OrgForm.js:24:23)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:100:14)
```
log 
```
function getScrollableContainer(n) {
  console.log(n.constructor.name)
  var keyNames = Object.keys(n);
   console.log(keyNames);
   console.log(n.hasOwnProperty('nodeName'))

}
```
give this result
```
 console.log node_modules/rc-form/lib/createDOMForm.js:58
    HTMLInputElement

  console.log node_modules/rc-form/lib/createDOMForm.js:60
    [ '__reactInternalInstance$x8vxl8cmjba',
      '__reactEventHandlers$x8vxl8cmjba',
      '_wrapperState',
      'value',
      '_valueTracker' ]

  console.log node_modules/rc-form/lib/createDOMForm.js:62
    false
```

**Comment by benjycui** [comment]
Please provide an online demo

**Comment by videni** [comment]
this only happen in jsdom, I am trying to write a test.

**Comment by cyberSane** [comment]
@videni , how to fixed it? i am facing the same problem while writing test.
