### ISSUE TITLE
执行npm start报错

### ISSUE THREAD

**Issue by xuhongxin** [react-component/form#421]
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/xuhongxin/codes/form/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/xuhongxin/codes/form/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/xuhongxin/codes/form/node_modules/fs-extra/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)

**Comment by yoyo837** [comment]
https://github.com/react-component/input-number/issues/249#issuecomment-636625129
